---
launchpad: os-client-config
team: OpenStackClient
type: library
release-model: cycle-with-intermediary
releases:
  - version: 0.3.0
    projects:
      - repo: openstack/os-client-config
        hash: fc0b80ed3b80012ffef493ea287e88e5909a160c
  - version: 0.4.0
    projects:
      - repo: openstack/os-client-config
        hash: 868d4dd9287a58154418a8d8c7624c423b9e8956
  - version: 0.4.1
    projects:
      - repo: openstack/os-client-config
        hash: 2bbcb630144975d032ecc312177a11266c2ac57b
  - version: 0.4.2
    projects:
      - repo: openstack/os-client-config
        hash: 89d1e4d3c4cbbe67d60c5b96cfb8ae6762737fd2
  - version: 0.4.3
    projects:
      - repo: openstack/os-client-config
        hash: 7385528671ea61617d7027fc33897ea850e7364c
  - version: 0.5.0
    projects:
      - repo: openstack/os-client-config
        hash: 07d340688474aceab85eeddc9468fac83396526d
  - version: 0.6.0
    projects:
      - repo: openstack/os-client-config
        hash: d5931d4658b43b5451adc38be5d6b7f257291098
  - version: 0.7.0
    projects:
      - repo: openstack/os-client-config
        hash: 79a1c489a2fa72ee26f7434dd8b443b69c403a4d
  - version: 0.8.0
    projects:
      - repo: openstack/os-client-config
        hash: b55de0e1637b1e9f6e424b070d13577af42d7fc6
repository-settings:
  openstack/os-client-config: {}
