---
launchpad: os-apply-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-apply-config: {}
releases:
  - projects:
      - hash: 7234780bae671b5fead73c00ff4d76221768ccd6
        repo: openstack/os-apply-config
    version: 10.4.0
  - version: 10.4.1
    projects:
      - repo: openstack/os-apply-config
        hash: d9df1dbd367d42430aa9abfe90d5aec572ec152b
