---
launchpad: os-net-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-net-config: {}
releases:
  - projects:
      - hash: 115c36b892b6757d0fcf56db6f146a7aed325ccd
        repo: openstack/os-net-config
    version: 11.0.0
  - projects:
      - hash: 564bd19d64b20611b187241fdc27f7c10dc1cbbe
        repo: openstack/os-net-config
    version: 11.1.0
  - version: 11.2.0
    projects:
      - repo: openstack/os-net-config
        hash: a74bbdd7b017fb3bb9faffb4240efa59cb42c79c
  - version: 11.3.0
    projects:
      - repo: openstack/os-net-config
        hash: 2ec6d366ee694e3540eac6ba702e73d9a210c366
branches:
  - name: stable/train
    location: 11.3.0
release-notes: https://docs.openstack.org/releasenotes/os-net-config/train.html
