---
launchpad: os-client-config
releases:
  - version: 1.8.0
    projects:
      - repo: openstack/os-client-config
        hash: 1629ae0d1f21dfca0b3f55d23541c61a5a666aca
    highlights: >
      Bugfixes. Added SWITCHengines to vendor list. Properly handle
      OS_CLOUD and OS_REGION_NAME when mixing ansible and openstackclient.
  - version: 1.8.1
    projects:
      - repo: openstack/os-client-config
        hash: 379962f0e8289e2db85a0eeb7b51d10cff70e67d
  - version: 1.9.0
    projects:
      - repo: openstack/os-client-config
        hash: 790fac98542ba303274180831cbd9a03604a84e8
    highlights: >
      Cleaned up the interface around cache config and added a per-resource
      cache config option based on nodepool needs. Added validation that
      region names are in the provided region name list if such a list exists.
