---
launchpad: oslo.config
releases:
  - version: 2.5.0
    projects:
      - repo: openstack/oslo.config
        hash: ddaddba5e5f6499608836b646e6435c15756ec70
  - version: 2.6.0
    projects:
      - repo: openstack/oslo.config
        hash: ee2bab65e9a2f38bb915f106a4da1520e4b5060c