---
launchpad: oslo.config
send-announcements-to: openstack-dev@lists.openstack.org
releases:
  - version: 2.5.0
    projects:
      - repo: openstack/oslo.config
        hash: ddaddba5e5f6499608836b646e6435c15756ec70
  - version: 2.6.0
    projects:
      - repo: openstack/oslo.config
        hash: ee2bab65e9a2f38bb915f106a4da1520e4b5060c
  - version: 2.7.0
    projects:
      - repo: openstack/oslo.config
        hash: 260891bd1ae3b168ba3f9e59c9d68f1a757c0830
  - version: 3.0.0
    projects:
      - repo: openstack/oslo.config
        hash: 9dd719f83aa888efee7f9bcbc8799e86b2ec8504
  - version: 3.1.0
    projects:
      - repo: openstack/oslo.config
        hash: 8cd41466d36a359482f6ed7cc0b1c919541f5461
  - version: 3.2.0
    projects:
      - repo: openstack/oslo.config
        hash: 26eef40f0cc0eba83cab4319667278f9aa741955
  - version: 3.2.1
    projects:
      - repo: openstack/oslo.config
        hash: e2e368bd1dd741c37888a5bba90bdec4de96a888