---
launchpad: os-apply-config
release-model: cycle-with-intermediary
release-type: python-pypi
branches:
  - location: 7.1.0
    name: stable/pike
releases:
  - projects:
      - hash: dcc453a946a98532e5f0b68ebcc52f96a56fb7cb
        repo: openstack/os-apply-config
    version: 7.0.0.0b1
  - projects:
      - hash: 89b0ba7bc424e1e10fdf1d269f819a4e612f9358
        repo: openstack/os-apply-config
    version: 7.0.0
  - projects:
      - hash: c2e15c8424de6ee260bc7266f813030d62246945
        repo: openstack/os-apply-config
    version: 7.1.0
  - projects:
      - hash: 1587707645de0fa45e29c0c16f8520175e82b940
        repo: openstack/os-apply-config
    version: 7.2.0
  - projects:
      - hash: 294cd491b585dcdeb199d3d8c3fc0160707ccefe
        repo: openstack/os-apply-config
    version: 7.2.1
  - projects:
      - hash: b70958677a775fb4e0c9fa1c22bdfe29e70aabd3
        repo: openstack/os-apply-config
    version: 7.2.2
team: tripleo
type: other
