---
launchpad: os-net-config
release-model: cycle-with-milestones
releases:
- projects:
  - hash: d12f1615cc006a09a232ecd7e3b75000a1af6d21
    repo: openstack/os-net-config
  version: 7.0.0.0b1
send-announcements-to: openstack-announce@lists.openstack.org
team: tripleo
type: other
