---
launchpad: os-net-config
release-model: cycle-with-intermediary
releases:
- projects:
  - hash: d12f1615cc006a09a232ecd7e3b75000a1af6d21
    repo: openstack/os-net-config
  version: 7.0.0.0b1
- projects:
  - hash: e7e81ac01122dd1b7711116d583a69fb655e0bca
    repo: openstack/os-net-config
  version: 7.0.0
team: tripleo
type: other
