---
launchpad: os-net-config
release-model: cycle-with-intermediary
release-type: python-pypi
branches:
  - location: 7.2.0
    name: stable/pike
releases:
  - projects:
      - hash: d12f1615cc006a09a232ecd7e3b75000a1af6d21
        repo: openstack/os-net-config
    version: 7.0.0.0b1
  - projects:
      - hash: e7e81ac01122dd1b7711116d583a69fb655e0bca
        repo: openstack/os-net-config
    version: 7.0.0
  - projects:
      - hash: 9ef9a7a92dc7af2a7d54affd68aaa37539296dd4
        repo: openstack/os-net-config
    version: 7.1.0
  - projects:
      - hash: 69fca4aa70b12d8eed2428c27deb62c46d605770
        repo: openstack/os-net-config
    version: 7.2.0
  - projects:
      - hash: 77fe5922bd7ca5c2a199d383b03537c08edfcc1c
        repo: openstack/os-net-config
    version: 7.3.0
  - projects:
      - hash: 9ce34d529d7faa65cfa6f88aaecf735f92c4c89b
        repo: openstack/os-net-config
    version: 7.3.1
  - projects:
      - hash: d71230766001743c9fac6faa683e3bdba98e3048
        repo: openstack/os-net-config
    version: 7.3.2
  - projects:
      - hash: 8c7dd0c014ae12de685458206a484bd4346da28d
        repo: openstack/os-net-config
    version: 7.3.3
team: tripleo
type: other
repository-settings:
  openstack/os-net-config: {}
