---
launchpad: os-refresh-config
release-model: cycle-with-milestones
releases:
- projects:
  - hash: 519606f749bb7787c040992f7c2b1baa8059ea6a
    repo: openstack/os-refresh-config
  version: 7.0.0.0b1
send-announcements-to: openstack-announce@lists.openstack.org
team: tripleo
type: other
