---
launchpad: os-refresh-config
release-model: cycle-with-intermediary
release-type: python-pypi
branches:
  - location: 7.0.0
    name: stable/pike
releases:
  - projects:
      - hash: 519606f749bb7787c040992f7c2b1baa8059ea6a
        repo: openstack/os-refresh-config
    version: 7.0.0.0b1
  - projects:
      - hash: f80ee22e8c3306ce5f4bb4220c870638cced33ae
        repo: openstack/os-refresh-config
    version: 7.0.0
  - projects:
      - hash: 4848c63cfed5236bf3450167e79cff723895d633
        repo: openstack/os-refresh-config
    version: 7.1.0
team: tripleo
type: other
repository-settings:
  openstack/os-refresh-config: {}
