---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
send-announcements-to: openstack-dev@lists.openstack.org
team: oslo
type: library
releases:
- version: 3.23.0
  projects:
  - repo: openstack/oslo.config
    hash: e53c79ebbb0f31db3bdf64760551f357b50c08a7
- version: 3.24.0
  projects:
  - repo: openstack/oslo.config
    hash: efb287a94645b15b634e8c344352696ff85c219f
- version: 4.0.0
  projects:
  - repo: openstack/oslo.config
    hash: 4cc7c6cb9bd96c986680241bbf2d3d454bcba246
- version: 4.1.0
  projects:
  - repo: openstack/oslo.config
    hash: 12fd34b963f6efa1bd8afd8ce06de33c90135f6d
- version: 4.1.1
  projects:
  - repo: openstack/oslo.config
    hash: 3290830993094d8bfebaabd499ffd825bffdb3a6
- version: 4.2.0
  projects:
  - repo: openstack/oslo.config
    hash: f0a915f5969a815b6469f56b88f9e346e394a733
