---
launchpad: openstack-requirements
team: requirements
type: other
include-pypi-link: yes
release-model: cycle-with-intermediary
stable-branch-type: tagless
releases:
  - version: 1.1.0
    projects:
      - repo: openstack/requirements
        hash: f5ce4279b968d04674ea32052cfe83f9a1aaddb8
        tarball-base: openstack_requirements
