---
launchpad: oslo.config
team: oslo
send-announcements-to: openstack-dev@lists.openstack.org
releases:
  - version: 1.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 059579ac2189b94bc9e9555b2e9acfb31a83ef53
