---
launchpad: os-net-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
releases:
  - projects:
      - hash: 44f3957b9ef1fa15797520ee1f0e3fc42e0c2b27
        repo: openstack/os-net-config
    version: 8.0.0
  - projects:
      - hash: bb7d8296d7a27ed2ddd9702b56c1fb0d6ae37b6e
        repo: openstack/os-net-config
    version: 8.1.0
  - projects:
      - hash: 123ddf0df4e0a5d95952c47dc9fe1021427a4209
        repo: openstack/os-net-config
    version: 8.2.0
repository-settings:
  openstack/os-net-config: {}
branches:
  - location: 8.2.0
    name: stable/queens
