---
launchpad: os-refresh-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
releases:
  - projects:
      - hash: 1c38f870605c65cbc61d718266ed0798d9a479ba
        repo: openstack/os-refresh-config
    version: 8.0.0
  - projects:
      - hash: e6f3b30ed50b6ac53f1ea8943f31ad8a548f687d
        repo: openstack/os-refresh-config
    version: 8.1.0
  - projects:
      - hash: 663a24638d4b856c65d5dd693efe135452ff9df8
        repo: openstack/os-refresh-config
    version: 8.2.0
repository-settings:
  openstack/os-refresh-config: {}
