---
include-pypi-link: yes
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
releases:
  - version: 4.12.0
    projects:
      - repo: openstack/oslo.config
        hash: 7fde851f8dc7ab0a4b796c2bba0e166f226e7674
  - projects:
      - hash: e6749d3208cffd7693353385f92865d9ac737623
        repo: openstack/oslo.config
    version: 4.13.0
  - projects:
      - hash: 0cce0be52abddc670f8d7451f240481eaa9fe208
        repo: openstack/oslo.config
    version: 4.13.1
  - projects:
      - hash: 36aded18660fc4d515aaabfc7bf1afbfb65e6411
        repo: openstack/oslo.config
    version: 4.13.2
