---
launchpad: os-collect-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
releases:
  - projects:
      - hash: 7de2fd8444fc4e42b86ecf91849f658cdf5d196e
        repo: openstack/os-collect-config
    version: 9.0.0
  - projects:
      - hash: 5bebbf1654f8eea8d74a4e403ac6bd3331a7fedf
        repo: openstack/os-collect-config
    version: 9.1.0
  - projects:
      - hash: 8763b70935068fef63887afdba683dcd6d4e0748
        repo: openstack/os-collect-config
    version: 9.2.0
  - projects:
      - hash: f63f4d2dc8e6de98edee861642eb2c204800f7cf
        repo: openstack/os-collect-config
    version: 9.2.1
  - version: rocky-em
    projects:
      - repo: openstack/os-collect-config
        hash: f63f4d2dc8e6de98edee861642eb2c204800f7cf
  - version: rocky-eol
    projects:
      - repo: openstack/os-collect-config
        hash: 88a863180861bcb7e27a6bf8703c4ad4b1558c00
branches:
  - location: 9.2.0
    name: stable/rocky
