---
include-pypi-link: yes
launchpad: os-client-config
release-model: cycle-with-intermediary
team: OpenStackSDK
type: library
repository-settings:
  openstack/os-client-config: {}
releases:
  - projects:
      - hash: cf5f446f27a08a41366847e2b586c51f9a6d696f
        repo: openstack/os-client-config
    version: 1.30.0
  - projects:
      - hash: 5c2eae8f8242332aff59d18b45a7d17f01524aaa
        repo: openstack/os-client-config
    version: 1.31.0
