---
include-pypi-link: yes
launchpad: os-client-config
release-model: cycle-with-intermediary
team: OpenStackSDK
type: library
repository-settings:
  openstack/os-client-config: {}
releases:
  - projects:
      - hash: cf5f446f27a08a41366847e2b586c51f9a6d696f
        repo: openstack/os-client-config
    version: 1.30.0
  - projects:
      - hash: 5c2eae8f8242332aff59d18b45a7d17f01524aaa
        repo: openstack/os-client-config
    version: 1.31.0
  - projects:
      - hash: a21123c384e6ff11269b7e6056f940de48413cab
        repo: openstack/os-client-config
    version: 1.31.1
  - projects:
      - hash: a024da3618c4a2a69eca0d83f6e4b34fa25643ca
        repo: openstack/os-client-config
    version: 1.31.2
branches:
  - location: 1.31.2
    name: stable/rocky
release-notes: https://docs.openstack.org/releasenotes/os-client-config/rocky.html
