---
launchpad: os-net-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: trailing
repository-settings:
  openstack/os-net-config: {}
releases:
  - version: 12.4.0
    projects:
      - repo: openstack/os-net-config
        hash: 869d3c13e84c9ccd0944ca8d8854d136c2854f17
  - version: 12.5.0
    projects:
      - repo: openstack/os-net-config
        hash: bca47783bc80999711084eefe499a6a1a9f3628e
  - version: 12.6.0
    projects:
      - repo: openstack/os-net-config
        hash: 933aaf80b14a100b1e5456b82536f8baf62ff01c
