---
include-pypi-link: true
storyboard: openstack/os-client-config
release-model: cycle-with-intermediary
team: OpenStackSDK
type: library
repository-settings:
  openstack/os-client-config: {}
releases:
  - version: 2.0.0
    projects:
      - repo: openstack/os-client-config
        hash: efd56a806e5d1ffad3dc8f31116c7e045b81ad04
