---
branches:
  - location: 6.0.0.0rc1
    name: stable/ocata
launchpad: os-apply-config
release-model: cycle-with-milestones
release-type: python-pypi
releases:
  - projects:
      - hash: 1bd0206930e9af8e91f7eae6878530c6a7968910
        repo: openstack/os-apply-config
    version: 6.0.0.0rc1
  - diff-start: 5.0.0
    projects:
      - hash: 1bd0206930e9af8e91f7eae6878530c6a7968910
        repo: openstack/os-apply-config
    version: 6.0.0
  - projects:
      - hash: ed286dcdd0eef0ea6703a73f893c03272b5ab9a5
        repo: openstack/os-apply-config
    version: 6.1.0
  - projects:
      - hash: 92f6066d62eef4282f6b1484c7d47e68f21be243
        repo: openstack/os-apply-config
    version: 6.1.1
  - projects:
      - hash: 9fa6f2dd4fe9a6f0414741d2e5c60ca7518f73e9
        repo: openstack/os-apply-config
    version: 6.1.2
  - projects:
      - hash: 7671343e5b7912bb152ef26e9076589f79a4a341
        repo: openstack/os-apply-config
    version: 6.1.3
team: tripleo
type: other
