---
launchpad: os-client-config
team: OpenStackClient
type: library
release-model: cycle-with-intermediary
send-announcements-to: openstack-dev@lists.openstack.org
include-pypi-link: yes
release-notes: http://docs.openstack.org/releasenotes/os-client-config/newton.html
releases:
  - version: 1.22.0
    projects:
      - repo: openstack/os-client-config
        hash: 6c252384c2cff4eef68d93e33d9bf81c9b768d38
    highlights: >
      Fixed an attribute error caused by a name type and added a setter method
      for configuring Session constructor wrappers.
  - version: 1.23.0
    projects:
      - repo: openstack/os-client-config
        hash: ba57e4f509f3ba8768027b29e9233252148f1eef
    highlights: >
      Add work-around for volumev3 service type, add fuga.io to vendors
