---
launchpad: os-cloud-config
team: tripleo
type: other
release-model: cycle-with-milestones
send-announcements-to: openstack-announce@lists.openstack.org
releases:
  - version: 6.0.0.0b1
    projects:
      - repo: openstack/os-cloud-config
        hash: f206fd88e4885e5c945a7b726971c99da0b09d11
  - version: 6.0.0.0b2
    projects:
      - repo: openstack/os-cloud-config
        hash: 9b0918551c68083e3226341cb97ddd03aa5229e6
