---
branches:
  - location: 6.0.0.0rc1
    name: stable/ocata
launchpad: os-collect-config
release-model: cycle-with-milestones
release-type: python-pypi
releases:
  - projects:
      - hash: e8e2f3d5f2ebc6c08383bf98e5e27c689fc6e7a1
        repo: openstack/os-collect-config
    version: 6.0.0.0b1
  - projects:
      - hash: bf7cc362d3928aedc2b48f1ffe871436b47b9483
        repo: openstack/os-collect-config
    version: 6.0.0.0b2
  - projects:
      - hash: cb846967f7d8e1f0a14f53e747ea5623e0a559d8
        repo: openstack/os-collect-config
    version: 6.0.0.0rc1
  - diff-start: 5.0.0
    projects:
      - hash: cb846967f7d8e1f0a14f53e747ea5623e0a559d8
        repo: openstack/os-collect-config
    version: 6.0.0
  - projects:
      - hash: 386cedabf7f38e2f8324b31d566de45457a5a04f
        repo: openstack/os-collect-config
    version: 6.1.0
  - projects:
      - hash: 7154ef294d59825cb6d849c4674efe949055dc6c
        repo: openstack/os-collect-config
    version: 6.1.1
  - projects:
      - hash: 88f02627983bdd53b2e9bdfaa7066582dbe12e27
        repo: openstack/os-collect-config
    version: 6.1.2
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
