---
launchpad: os-net-config
team: tripleo
type: other
release-model: cycle-with-milestones
send-announcements-to: openstack-announce@lists.openstack.org
releases:
  - version: 6.0.0.0b1
    projects:
      - repo: openstack/os-net-config
        hash: e479535b508b4072f64300809b824dfecc3a9182
