---
launchpad: oslo.config
send-announcements-to: openstack-dev@lists.openstack.org
include-pypi-link: true
releases:
- version: 3.18.0
  projects:
  - repo: openstack/oslo.config
    hash: d57e5380be1d829b15ce1ba14ce659c501fccac4
team: oslo
