---
launchpad: os-apply-config
team: tripleo
type: other
release-model: cycle-with-milestones
send-announcements-to: openstack-announce@lists.openstack.org
branches:
  - name: stable/newton
    location: 5.0.0
releases:
  - version: 5.0.0.0b1
    projects:
      - repo: openstack/os-apply-config
        hash: 36f24df3e79e7c0f3621e8231853342b4f89d0e8
  - version: 5.0.0.0b2
    projects:
      - repo: openstack/os-apply-config
        hash: 69879dad8b66933f79c7e06d159ef2e91160aa1e
  - version: 5.0.0
    diff-start: 0.1.32
    projects:
      - repo: openstack/os-apply-config
        hash: 69879dad8b66933f79c7e06d159ef2e91160aa1e
