---
launchpad: os-client-config
team: OpenStack client
send-announcements-to: openstack-dev@lists.openstack.org
include-pypi-link: yes
releases:
  - version: 1.17.0
    projects:
      - repo: openstack/os-client-config
        hash: 5605034fc38862b19e6d2d96aa222dafc7762060
    highlights: >
      Added a more flexible mechanism for conveying network metadata.
  - version: 1.18.0
    projects:
      - repo: openstack/os-client-config
        hash: 51b4cbee522e2bf1a2beb12425733435ff1c32d9
    highlights: >
      Added helper factory functions for OpenStack SDK and shade.
  - version: 1.19.0
    projects:
      - repo: openstack/os-client-config
        hash: 8e4a1ebc97d30bcaf42a94379d499bd1689c3c51
    highlights: >
      Add profile deprecation setting, OSC 3.0 support
