---
branches:
  - location: 5.0.0
    name: stable/newton
launchpad: os-collect-config
release-model: cycle-with-milestones
release-type: python-pypi
releases:
  - projects:
      - hash: a88e2733a7c801ce9cda2b25fbdd1b0fc66ade99
        repo: openstack/os-collect-config
    version: 5.0.0.0b1
  - projects:
      - hash: c2bdb4f672b6984ee2ff511f07d7950712454acc
        repo: openstack/os-collect-config
    version: 5.0.0.0b3
  - projects:
      - hash: 9ee07c96c2b0d64485d111aed0af03fa394e9c4d
        repo: openstack/os-collect-config
    version: 5.0.0.0rc2
  - diff-start: 0.1.37
    projects:
      - hash: 9ee07c96c2b0d64485d111aed0af03fa394e9c4d
        repo: openstack/os-collect-config
    version: 5.0.0
  - projects:
      - hash: 3d7835dc5a63802202209e7f1d096d272608550d
        repo: openstack/os-collect-config
    version: 5.1.0
  - projects:
      - hash: 3d7835dc5a63802202209e7f1d096d272608550d
        repo: openstack/os-collect-config
    version: 5.2.0
  - projects:
      - hash: bbd95e655f31f313c12684e4f2d2cbae447a0cf7
        repo: openstack/os-collect-config
    version: 5.2.1
  - projects:
      - hash: d5a2dc714c0ab5e516fd6a53ba84e88c3e083fc7
        repo: openstack/os-collect-config
    version: newton-eol
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
