---
launchpad: os-collect-config
team: tripleo
send-announcements-to: openstack-announce@lists.openstack.org
releases:
  - version: 5.0.0.0b1
    projects:
      - repo: openstack/os-collect-config
        hash: a88e2733a7c801ce9cda2b25fbdd1b0fc66ade99
  - version: 5.0.0.0b3
    projects:
      - repo: openstack/os-collect-config
        hash: c2bdb4f672b6984ee2ff511f07d7950712454acc
