---
launchpad: os-collect-config
send-announcements-to: openstack-announce@lists.openstack.org
releases:
  - version: 5.0.0.0b1
    projects:
      - repo: openstack/os-collect-config
        hash: a88e2733a7c801ce9cda2b25fbdd1b0fc66ade99
