---
launchpad: os-net-config
send-announcements-to: openstack-announce@lists.openstack.org
releases:
  - version: 5.0.0.0b1
    projects:
      - repo: openstack/os-net-config
        hash: 60475755e3750b2d2e047578a68c8c2327bf50d7
