---
branches:
  - location: 5.0.0
    name: stable/newton
launchpad: os-net-config
release-model: cycle-with-milestones
release-type: python-pypi
releases:
  - projects:
      - hash: 60475755e3750b2d2e047578a68c8c2327bf50d7
        repo: openstack/os-net-config
    version: 5.0.0.0b1
  - projects:
      - hash: 6bb8412ef3d3f163d91f2884081b743f07a78f18
        repo: openstack/os-net-config
    version: 5.0.0.0b2
  - projects:
      - hash: f79d534c3e130bb539cf7ccb1d3f9586e922b9a7
        repo: openstack/os-net-config
    version: 5.0.0.0b3
  - projects:
      - hash: 35823f261506f9256c1a227dd4a2770a0508c62d
        repo: openstack/os-net-config
    version: 5.0.0.0rc2
  - diff-start: 0.2.4
    projects:
      - hash: 35823f261506f9256c1a227dd4a2770a0508c62d
        repo: openstack/os-net-config
    version: 5.0.0
  - projects:
      - hash: 594d3f4692bf158b041709b03cc17789698ae6f1
        repo: openstack/os-net-config
    version: 5.1.0
  - projects:
      - hash: 3471ff7ba99bec5310a44e9363eafd4709d89026
        repo: openstack/os-net-config
    version: 5.2.0
  - projects:
      - hash: 60e32735b115b0d6ba7511db8dd3b44e2795a641
        repo: openstack/os-net-config
    version: 5.2.1
  - projects:
      - hash: f8ac86541fa1e0f49313b96941436428d386ab2b
        repo: openstack/os-net-config
    version: 5.2.2
  - projects:
      - hash: 2c7c5e66a7a7393745d67e46de23e69c0f2d4733
        repo: openstack/os-net-config
    version: 5.2.3
  - projects:
      - hash: 91e3ac46ef7976a06c8cc6572ef6591f0e733f16
        repo: openstack/os-net-config
    version: 5.2.4
team: tripleo
type: other
repository-settings:
  openstack/os-net-config: {}
