---
launchpad: os-refresh-config
team: tripleo
type: other
release-model: cycle-with-milestones
send-announcements-to: openstack-announce@lists.openstack.org
branches:
  - name: stable/newton
    location: 5.0.0
releases:
  - version: 5.0.0.0b1
    projects:
      - repo: openstack/os-refresh-config
        hash: 08b517491f61cb17b46ea783b70ce079330294ae
  - version: 5.0.0.0b2
    projects:
      - repo: openstack/os-refresh-config
        hash: 1d828fa0dd91bb1e1824883e3202da2e8dfa148e
  - version: 5.0.0.0b3
    projects:
      - repo: openstack/os-refresh-config
        hash: 1d828fa0dd91bb1e1824883e3202da2e8dfa148e
  - version: 5.0.0
    diff-start: 0.1.11
    projects:
      - repo: openstack/os-refresh-config
        hash: 1d828fa0dd91bb1e1824883e3202da2e8dfa148e
  - version: 5.1.0
    projects:
      - repo: openstack/os-refresh-config
        hash: 8b3d3f8e12f73ddaa80f16c56c6fac948a940a14
