---
launchpad: oslo.config
team: oslo
send-announcements-to: openstack-dev@lists.openstack.org
include-pypi-link: true
releases:
- version: 3.10.0
  projects:
  - repo: openstack/oslo.config
    hash: 6d176243f398bf7e5d6bd8a5382945f2c5e318c3
  highlights: |-
    * Avoid duplicate sections in generator output
    * Don't set html_last_updated_fmt without git
    * Improve documentation about registering entry points for
      config generator
- version: 3.11.0
  projects:
  - repo: openstack/oslo.config
    hash: bb0f7e3880bd83dbb9088f3f8045152ce8e7897b
  highlights: |-
    * Return [] for .config_dirs when config files are not parsed
    * Incorrect group name when deprecated_group is not specified
    * Disallow config option name as same as attribute of ConfigOpts
- version: 3.12.0
  projects:
  - repo: openstack/oslo.config
    hash: d8e71b9d10132a9c134ff79a4ecdc77d17d424be
  highlights: |-
    * Adds a new option, URIOpt
    * Adds deprecated_since parameter
    * Handle some native python types in config generation
    * Support template substitution of DictOpt
    * Allow for specifying minimal configuration (not required)
- version: 3.13.0
  projects:
  - repo: openstack/oslo.config
    hash: 11456e00c4152f393119c2ba33eceaa0f5d02b4d
  highlights: |-
    * Enabling your project for mutable-config
    * Add Python 3.5 classifier and venv
