---
launchpad: os-collect-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
releases:
  - projects:
      - hash: 5c924cc95edc567beac0392702d31dea10831658
        repo: openstack/os-collect-config
    version: 10.0.0
