---
launchpad: os-collect-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
releases:
  - projects:
      - hash: 5c924cc95edc567beac0392702d31dea10831658
        repo: openstack/os-collect-config
    version: 10.0.0
  - projects:
      - hash: 830e028c72a1aaf72f675f286d63b976e92b8641
        repo: openstack/os-collect-config
    version: 10.1.0
  - projects:
      - hash: 6bdbc35fbcf0df7a1d03fa2ef31da4028f03a2da
        repo: openstack/os-collect-config
    version: 10.2.0
