---
launchpad: os-refresh-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-refresh-config: {}
releases:
  - projects:
      - hash: 2cdebc64e0a3b3064cc472c08cbede138497839d
        repo: openstack/os-refresh-config
    version: 10.0.0
  - projects:
      - hash: 4e9ce62c04eb13850fb40552033362464171255b
        repo: openstack/os-refresh-config
    version: 10.1.0
  - projects:
      - hash: d0277ff94839b636b013de8263debf285217b10a
        repo: openstack/os-refresh-config
    version: 10.2.0
