---
include-pypi-link: yes
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - projects:
      - hash: 7072a7552dcb58a60d08c73c1d002fdf1c5a6202
        repo: openstack/oslo.config
    version: 6.5.0
  - diff-start: 6.4.0
    projects:
      - comment: 'procedural tag to handle release job failure'
        hash: 7072a7552dcb58a60d08c73c1d002fdf1c5a6202
        repo: openstack/oslo.config
    version: 6.5.1
  - projects:
      - hash: ae7dbd939f76d84c0e4ee479f1c82aa4925d6e95
        repo: openstack/oslo.config
    version: 6.6.0
  - projects:
      - hash: d2ee0bf4069aea13c36599572bb38d0ed10966bb
        repo: openstack/oslo.config
    version: 6.6.1
  - projects:
      - hash: c09b80440a5b8055a67c36706e20ddd80110b4bf
        repo: openstack/oslo.config
    version: 6.6.2
  - projects:
      - hash: 64e020adbb5b31a1f6ffb01f84f049562f09c788
        repo: openstack/oslo.config
    version: 6.7.0
  - projects:
      - hash: 8e17ded72a4ff0a31712d4b65c80c0490938d596
        repo: openstack/oslo.config
    version: 6.8.0
  - projects:
      - hash: fd4c1a0bf46505136609749479b138bd4ffe1140
        repo: openstack/oslo.config
    version: 6.8.1
