---
launchpad: os-cloud-config
team: tripleo
type: other
send-announcements-to: openstack-dev@lists.openstack.org
releases:
  - version: 0.2.7
    projects:
      - repo: openstack/os-cloud-config
        hash: 439f10136dbab6f0ebdd1d9002526345c02c055b
  - version: 0.2.8
    projects:
      - repo: openstack/os-cloud-config
        hash: d3168fe6fdb4be891f44636c66225ce73ecd39a2
  - version: 0.2.9
    projects:
      - repo: openstack/os-cloud-config
        hash: 95e9d4a3685037b2e70893e64764538a91a08df3
