---
launchpad: os-net-config
send-announcements-to: openstack-dev@lists.openstack.org
releases:
  - version: 0.1.4
    projects:
      - repo: openstack/os-net-config
        hash: a4a4c43f92138b7d477c7c944849fc69e3c21ac6
