---
launchpad: os-net-config
team: tripleo
type: other
send-announcements-to: openstack-dev@lists.openstack.org
include-pypi-link: yes
releases:
  - version: 0.1.4
    projects:
      - repo: openstack/os-net-config
        hash: a4a4c43f92138b7d477c7c944849fc69e3c21ac6
  - version: 0.2.4
    projects:
      - repo: openstack/os-net-config
        hash: 2188cf1651648af1900b7bb070f9b1eb3f982c3b
    highlights: |
      This release will set PEERDNS=no unless dns_servers
      is provided or use_dhcp is set for the interface.
