---
launchpad: os-refresh-config
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-refresh-config: {}
releases:
  - version: 13.0.0
    projects:
      - repo: openstack/os-refresh-config
        hash: 754bb751e6728aafa680111a6fab3013609654cc
