---
launchpad: labs
team: Documentation
type: other
stable-branch-type: tagless
branches:
  - name: stable/queens
    location:
      openstack/training-labs: b5a44c367b99a13af577248b354572e241734d7a
repository-settings:
  openstack/training-labs: {}
