---
launchpad: os-collect-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: trailing
repository-settings:
  openstack/os-collect-config: {}
# Note: deliverable was not released in victoria
